require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/*'
    - 'script/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
    - config/initializers/*
    - config/environments/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/initializers/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/views/**/*

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false


