default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DEFAULT_HOST'] %>
  username: <%= ENV['DEFAULT_USERNAME'] %>
  password: <%= ENV['DEFAULT_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE'] %>

production:
  host: <%= ENV['PRODUCTION_HOST'] %>
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['PRODUCTION_USERNAME'] %>
  password: <%= ENV['PRODUCTION_PASSWORD'] %>
